version: "3.0"

services:
  student-db:
    image: postgres:15.4-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      
