version: '3.0'
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - local_volume:/var/lib/postgresql
volumes:
  local_volume: