version: '3.0'
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - 5432:5432
    # env_file:
    #   - ../.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres_db
    volumes:
      - local_volume:/var/lib/postgresql
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=mongo_db
      - MONGO_INITDB_USERNAME=baba
      - MONGO_INITDB_PASSWORD=123
    volumes:
      - ./mongo_script/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      # - ./mongo_script/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo_db:/data/db
volumes:
  local_volume: